# Generated by Django 4.2.28 on 2026-02-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='drug',
        ),
        migrations.AddField(
            model_name='brand',
            name='drugs',
            field=models.ManyToManyField(related_name='brands', to='drugquizapp.drug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
