# Generated by Django 4.2.28 on 2026-03-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquizapp', '0002_remove_brand_drug_brand_drugs_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_combination',
            field=models.BooleanField(default=False),
        ),
    ]
