# Generated by Django 4.2.28 on 2026-03-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTHealthcareDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('mechanism', 'Mechanism'), ('indication', 'Indication'), ('side_effect', 'Side Effect'), ('contraindication', 'Contraindication'), ('interaction', 'Interaction'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='pthealthcare.pthealthcaredrug')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
