# Generated by Django 4.2.29 on 2026-04-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pthealthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pthealthcaredrug',
            name='drug_class',
        ),
        migrations.AddField(
            model_name='pthealthcaredrug',
            name='drug_class',
            field=models.ManyToManyField(blank=True, to='pthealthcare.drugclass'),
        ),
    ]
