# Generated by Django 4.2.29 on 2026-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pthealthcare', '0002_drugclass_remove_pthealthcaredrug_drug_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pthealthcaredrug',
            name='classes',
            field=models.ManyToManyField(blank=True, to='pthealthcare.drugclass'),
        ),
        migrations.RemoveField(
            model_name='pthealthcaredrug',
            name='drug_class',
        ),
        migrations.AddField(
            model_name='pthealthcaredrug',
            name='drug_class',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
